language: rust

rust:
  - stable
  - nightly

cache:
  cargo: true

sudo: required

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev

env:
  global:
  - RUSTFLAGS="-C link-dead-code"

script:
  - cargo build --verbose --all
  - cargo test --verbose --all

jobs:
  allow_failures:
    - rust: nightly-2018-03-03
  include:
    - stage: clippy lints
      rust: nightly-2018-03-03
      env:
        - NIGHTLY=nightly-2018-03-03
        - CLIPPY=0.0.187
      before_install:
        - travis_wait ./.ci/travis-install-clippy.sh
      script:
        - cargo +$NIGHTLY clippy --verbose --all -- -D warnings

    - stage: coverage
      rust: stable
      script:
        - ./.ci/travis-upload-coverage.sh

branches:
  only:
    - master
    - develop

notifications:
  email:
    on_success: never
